### ISSUE TITLE
Add an endpoint to initialize/reset the database

### ISSUE THREAD

**Issue by anandology** [pipalacademy/rajdhani#10]
A copy of the trains db will be available at https://rajdhani.pipal.in/static/trains.db

When the app starts, if the database file is not present, it should automatically download the db the above url before creating the database connection. 

We also need an endpoint to reset the database if something goes wrong. 

Make sure that the corrupt database should not stop the home page and reset page to function.

**Comment by nikochiko** [comment]
> Make sure that the corrupt database should not stop the home page and reset page to function

SQLAlchemy initializes an engine lazily after `create_engine`.
Would it work if I create a simple `get_engine()` or `get_conn()` wrapper around it that does this initialization with the correct db path?

Then as long as this is used only in `db.some_function()`, it would not cause a crash.

**Comment by nikochiko** [comment]
For the initialization, I have two patterns in mind:
- **Middleware for the whole app (or selectively for `/api/*`):** before serving request, check and initialize db if needed 
- **Inside get_engine() function:** checks if the file exists before creating an engine object

**Comment by anandology** [comment]
What if you call `db_ops.get_db_url()` at the begining of the db module and that would:

1. download the database file if not already present
2. check if the existing file is alright, if not return `:memory:` as database url after setting a global flag that db is corrupt

**Comment by anandology** [comment]
> 



> > Make sure that the corrupt database should not stop the home page and reset page to function
> 
> SQLAlchemy initializes an engine lazily after `create_engine`. Would it work if I create a simple `get_engine()` or `get_conn()` wrapper around it that does this initialization with the correct db path?
> 
> Then as long as this is used only in `db.some_function()`, it would not cause a crash. in other endpoints.

If the sqlalchemy already initilaized it lazily, a corrupt database will not break loading the app. We don't have to worry about it them. 

The only case that we need to take care is to make sure a db is there. You can just call `db_ops.ensure_db()` at the beginning of the db module.

**Comment by nikochiko** [comment]
That seems like a good idea! Will do.

**Comment by nikochiko** [comment]
done!
