### ISSUE TITLE
Add data explorer

### ISSUE THREAD

**Issue by anandology** [pipalacademy/rajdhani#11]
Add a data explorer to the app to enter a SQL query and see the result as a table. 

The webpage will have a textbox to enter a SQL query and the results will be displayed as a table. 

Also, link it from the top nav.

When the result has more than 100 rows, show the first 100 with a message "Showing 100 of xyz". 

## Layout

DATA EXPLORER

Explore the data by writing any SQL query. 

The database has two tables `train` and `station`. See schema [link to schema.py in the github].

Sample queries:

SELECT * FROM trains limit 10;
SELECT * FROM trains where from_station_code='SBC';
SELECT * FROM stations where state='Karnataka';

[TEXT BOX]

[RESULTS TABLE]

**Comment by nikochiko** [comment]
Done!
