### ISSUE TITLE
Better name for the project and domain

### ISSUE THREAD

**Issue by anandology** [pipalacademy/rajdhani#7]
I've been thinking of a better name for the project since we started it. 

What do you think of calling it **Rajdhani**? 
We could use the subtitle _Explore India by train_.

We can host it on domain `rajdhani.pipal.in` for now and every user will get `foo.rajdhani.pipal.in` domain. 

We may think of a top-level domain if we decide to launch it to the public.

What do you think @nikochiko?

## Tasks

- [x] rename the repository
- [x] rename the python package and fix imports

**Comment by nikochiko** [comment]
Done!

**Comment by anandology** [comment]
Could of comments:

Use `Flask(__name__)` instead of `Flask("rajdhani")`. The first one is a convention suggested by Flask and continues to work, even if we rename the module or package name.

Looks like you've accidentally committed the `config.py` changes as well. The `enable_homepage` is not set to `True`.

**Comment by nikochiko** [comment]
Oops. Corrected!

> Use Flask(\_\_name__) instead of Flask("rajdhani").

Then the name would be become rajdhani.app instead of just rajdhani, but I think that's okay.

Thanks for reviewing.

**Comment by anandology** [comment]
Done.
