### ISSUE TITLE
Production deploy of app

### ISSUE THREAD

**Issue by anandology** [pipalacademy/rajdhani#9]
Deploy the app on the new server `rajdhani.pipal.in` and document the deployment process.

**Comment by anandology** [comment]
I guess this issue should ideally belong to boring-serverless.

**Comment by anandology** [comment]
> I guess this issue should ideally belong to boring-serverless.

Well, not really. We are deploying rajdhani app using boring-serverless. It is fine to be in this repo.

**Comment by nikochiko** [comment]
done!

These were the deployment steps i had to follow for this.
Most of it is documented already in boring-serverless README.
Few steps I did extra were disabling nginx.service, installing dependencies of the app to be deployed manually (we may be able to improve this flow), and editing the github workflow for server_url

```
   git clone https://github.com/pipalacademy/boring-serverless
   cd boring-serverless

   sudo apt-get install python3.10-venv # python3.10 was installed on the system
   python3.10 -m venv venv
   venv/bin/python -m pip install -r requirements.txt

   cp config.yml.sample config.yml

   sudo apt-get install apache2
   vim deployment/etc/sites-available/apache2/boring.conf:
     - change <Directory >
     - change domain name in ServerName
     - change installation directory in RewriteRule
   sudo systemctl disable nginx.service # clear up port 80/443
   sudo a2enmod cgid rewrite
   sudo a2ensite boring
   sudo systemctl restart apache2.service

   sudo chmod +x /home/pipal # enable access to user home directory

   # install dependencies of rajdhani
   mkdir apps
   git clone https://github.com/pipalacademy/train-ride apps/pipalacademy
   venv/bin/python -m pip install -r apps/pipalacademy/requirements.txt
   rm -rf apps/pipalacademy

   # now edit the workflow in train-ride repo to point to the new server_url for boring:
   # boring.rajdhani.pipal.in
```

**Comment by nikochiko** [comment]
Added SSL.
https://boring.rajdhani.pipal.in

**Comment by nikochiko** [comment]
This is done

**Comment by anandology** [comment]
Can you make the deploy work at https://rajdhani.pipal.in/deploy ?

Also, we need to set up wildcard DNS for rajdhani.pipal.in. That required
using digitalocean DNS token.

**Comment by nikochiko** [comment]
These steps are outdated now and the up-to-date deployment docs are in Hamr's README.

> Can you make the deploy work at https://rajdhani.pipal.in/deploy ?

Deploy URL is `https://rajdhani.pipal.in/<app_name>/deploy`, for an existing app.

> Also, we need to set up wildcard DNS for rajdhani.pipal.in. That required
using digitalocean DNS token.

That step is documented in Hamr: https://github.com/pipalacademy/hamr#recommended
